jhudsl/intro_to_r

Data_Summarization/index.Rmd
Data_Summarization/lab/Data_Summarization_Lab.Rmd
Data_Summarization/lab/Data_Summarization_Lab_Key.Rmd

These changes pertain to the Data Summarization lecture

Summarization

---

Data_IO/index.Rmd

Bunch of minor changes, such as: reordering content slides (some content was lectured after it appeared in the lab), updating the arguments name (path into file in readr package functions), minor text changes. 
The links were changed from John's website to jhudsl's website.

Data io content updates

---

Data_IO/index.Rmd
Data_IO/lab/Data_IO_Lab.Rmd
Data_IO/lab/Data_IO_Lab_Key.Rmd

lightening the lecture and lab conent

update data IO

---

Data_Classes/index.Rmd
Data_Classes/lab/Data_Classes_Lab.Rmd
Data_Classes/lab/Data_Classes_Lab_Key.Rmd

update data classes content (slides + lab + lab key)

Data classes content updates

---

Data_Classes/index.Rmd

add slide explaining slicing/subsetting data from a vector

add slide about subsetting vectors

---

Functions/index.Rmd

It looks like I changed a lot but mostly rearranging!

Simplify functions examples

---

Statistics/index.Rmd
Statistics/lab/Statistics_Lab.Rmd
Statistics/lab/Statistics_Lab_Key.Rmd

Statistics content updates

---

Syllabus/module_details/day0.Rmd
Syllabus/module_details/day1.Rmd
Syllabus/module_details/day2.Rmd
Syllabus/module_details/day3.Rmd
Syllabus/module_details/day4.Rmd
Syllabus/module_details/day5.Rmd
Syllabus/module_details/day6.Rmd
Syllabus/module_details/day7.Rmd
Syllabus/module_details/day8.Rmd
Syllabus/module_details/day9.Rmd
Syllabus/syllabus.Rmd

@cansavvy this should fix the build issue due to the remnant google sheets. Continuation of problems caused in #70 🙂

Fix link to google sheet in module details

---

Basic_R/index.Rmd

A few changes to Basic_R section. 
1. Add a link to debugging guide 
2. Don't encourage using `=` for assignments.

Add basic R updates

---

.github/workflows/delete-preview.yml
.github/workflows/pull_request.yml
.github/workflows/render-site.yml

Adding the actions (that's it!)

Add actions

---

.github/workflows/render-site.yml

Forgot to update render site workflow!

Revamp website w actions

---

docs/module_details/day0.Rmd
docs/module_details/day1.Rmd
docs/module_details/day2.Rmd
docs/module_details/day3.Rmd
docs/module_details/day4.Rmd
docs/module_details/day5.Rmd
docs/module_details/day6.Rmd
docs/module_details/day7.Rmd
docs/module_details/day8.Rmd
docs/module_details/day9.Rmd
materials_schedule.Rmd

Fix links throughout

---

modules/Data_IO/Data_IO.Rmd

@carriewright11 do you think this adequately addresses #126 ?

Add more about haven

---

modules/Data_Cleaning/Data_Cleaning.Rmd
modules/Subsetting_Data_in_R/Subsetting_Data_in_R.Rmd

I added `which` to the subsetting lecture
`which` was then used in the cleaning lecture to show how to filter by percent missing.
This addresses #106  and #115

Percent missing & which

---

modules/Data_IO/Data_IO.Rmd
modules/Data_IO/lab/Data_IO_Lab.Rmd
modules/Data_IO/lab/Data_IO_Lab_Key.Rmd

Minor updates (summary, positional args, bonuses)

IO updates

---

docs/Contribute.md
docs/styles.css
modules/Data_Classes/Data_Classes.Rmd
modules/Data_Classes/lab/Data_Classes_Lab.Rmd
modules/Data_Classes/lab/Data_Classes_Lab_Key.Rmd
modules/Subsetting_Data_in_R/Subsetting_Data_in_R.Rmd

- also adding special formatting to general code structure for subsetting lecture
- adding colored text info to contribute.md
- updating class lecture with summaries and links and bit better organized
- removing table() from lab for class module for issue #117

Updates classes

---

modules/Subsetting_Data_in_R/lab/Subsetting_Data_in_R_Lab.Rmd
modules/Subsetting_Data_in_R/lab/Subsetting_Data_in_R_Lab_Key.Rmd

small changes to subsetting lab for clarity

---

modules/Subsetting_Data_in_R/Subsetting_Data_in_R.Rmd

adding green to general format in one more spot!

---

modules/Data_Classes/Data_Classes.Rmd
modules/Data_Summarization/Data_Summarization.Rmd
modules/Data_Summarization/lab/Data_Summarization_Lab.Rmd
modules/Data_Summarization/lab/Data_Summarization_Lab_Key.Rmd
resources/dictionary.txt

- Many miscellaneous improvements to wording and clarity
- Add summary at the end
- Add website buttons
- Recapped previous day
- Named some positional args where appropriate
- Add better hints to the lab
- Lab Bonuses
- Renamed to be more optional
- rearranged bonus to be under each lab section instead of all at the end

Updates to summarization prior to class

---

modules/Data_Classes/Data_Classes.Rmd
modules/Data_Cleaning/Data_Cleaning.Rmd
resources/dictionary.txt

- small fix to typo in classes
- adding recap for issue #169 
- not sure if I should remove separate and unite... need to check if unite is in manipulating data lecture

updates to cleanin lecture

---

resources.Rmd

adding rstudio shortcuts and file path help

adding more resources

---

modules/Subsetting_Data_in_R/Subsetting_Data_in_R.Rmd

- getting rid of `::`
- saying that rownames_to_column is from `tibble()`
- checked that glimpse says from dplyr 
- all for issue #185

small updates based on today

---

modules/Factors/Factors.Rmd
modules/Factors/lab/Factors_Lab.Rmd
modules/Factors/lab/Factors_Lab_Key.Rmd

Addressing issue: #179, #83 , #201 , #112, #180, #150, #122, #83
Also removing `tally()` - I don't think we had it in the `summarization` section but I might be mistaken. In any case summarize works and it is a little more clear what it is doing I think.
Otherwise just making things look nicer and more clear

Updates factors

---

modules/Manipulating_Data_in_R/Manipulating_Data_in_R.Rmd
modules/Manipulating_Data_in_R/lab/Manipulating_Data_in_R_Lab.Rmd
modules/Manipulating_Data_in_R/lab/Manipulating_Data_in_R_Lab_Key.Rmd

- Add summaries prior to lab
- Make lab link clear
- Add recap from last time, cheatsheet
- Overall cleanup and updates
- Make some questions in the lab bonus

Manipulation

---

modules/Esquisse_Data_Visualization/Esquisse_Data_Visualization.Rmd
modules/Esquisse_Data_Visualization/lab/Esquisse_Data_Visualization_Lab.Rmd
modules/Esquisse_Data_Visualization/lab/Esquisse_Data_Visualization_Lab_Key.Rmd

Pretty straightforward - minor changes

Update lecture and lab for Esquisse

---

.github/workflows/render-site.yml

Moving this - hopefully fixes the pdf rendering issue

Move commit and pull around

---

.github/workflows/render-site.yml

I was editing on github :P previously, apparently I am not as good at that haha

fixing extra line in render-site.yml

---

.github/workflows/render-site.yml

didn't mean to keep both names of the action - again I should only edit not on GitHub :P

I think it is mad about the two names

---

.github/workflows/pull_request.yml

Realized the previous pdf action was also in this workflow too

updating fisky pdf conversion action in pull_request

---

.github/workflows/pull_request.yml
.github/workflows/render-site.yml

This should resolve #238 I think...

updating checkout version

---

.github/workflows/render-site.yml

for issue #239 - not sure if it will resolve it
trying to reduce when the event happens on the main branch

attempting to fix rendering loop

---

.github/workflows/render-site.yml

Moving run_if statement so that there are steps... for issue #239 
We will see if this helps

moving run_if statements

---

.github/workflows/render-site.yml

removing run_if to just if

---

.github/workflows/render-site.yml

moving the if statement to earlier again

still trying to fix Render loop

---

.github/workflows/pull_request.yml
.github/workflows/render-site.yml

doing it like the pull_request workflow which  has been working
- also updating checkout for pull_request workflow to reduce warnings

using same credentials for render_site 

---

modules/HW/homework2.Rmd
modules/HW/homework2_key.Rmd
modules/HW/homework3.Rmd
modules/HW/homework3_key.Rmd

just changed the deadlines for all homework to Jan 25th!

updating the deadlines on the homework files for winter23

---

.github/workflows/render-site.yml
modules/Intro/Intro.Rmd

fixing the date on intro and trying to fix the continual rendering issue

---

docs/module_details/day0.Rmd
modules/Setup/R_and_RStudio_installation.Rmd

- Correcting version in Rstudio setup details 
- Removing link to old playlist

Day 0 assignment tweaks

---

modules/Subsetting_Data_in_R/Subsetting_Data_in_R.Rmd

Subsetting23

---

modules/Basic_R/Basic_R.Rmd
modules/Basic_R/lab/Basic_R_Lab.Rmd
modules/Basic_R/lab/Basic_R_Lab_Key.Rmd
modules/Data_Input/Data_Input.Rmd

Finalizing recap
starts to address #177

Add Final changes to Basic R

---

modules/Subsetting_Data_in_R/Subsetting_Data_in_R.Rmd
modules/Subsetting_Data_in_R/lab/Subsetting_Data_in_R_Lab_Key.Rmd

- removing data output from recap
- more about quotes and backticks
- discussion about base R

Final edits for subsetting

---

modules/Data_Cleaning/Data_Cleaning.Rmd

- making some things simpler so people don't get confused
- also making some things look better on slides

Cleaning23

---

modules/HW/homework2_key.Rmd
modules/Manipulating_Data_in_R/Manipulating_Data_in_R.Rmd
modules/Manipulating_Data_in_R/lab/Manipulating_Data_in_R_Lab.Rmd
modules/Manipulating_Data_in_R/lab/Manipulating_Data_in_R_Lab_Key.Rmd

- Clarify language
- Add a question about `read.csv()` to the lab -good learning opportunity
- Clean up formatting and directions in lab
Resolves #217

Manipulating Data updates for Winter 2023!

---

modules/Basic_R/lab/Basic_R_Lab_Key.Rmd

Fix typo in Lab

---

modules/Esquisse_Data_Visualization/Esquisse_Data_Visualization.Rmd
modules/Esquisse_Data_Visualization/lab/Esquisse_Data_Visualization_Lab_Key.Rmd
quotes_vs_backticks.Rmd

Resolves #209 
Also describes how pivot_longer and pivot_wider need quotes for column names if you make new ones

Esquisser and backticks and quotes resource

---

modules/Data_Visualization/Data_Visualization.Rmd

cake was set at really small size

---

modules/Statistics/Statistics.Rmd
modules/Statistics/lab/Statistics_Lab.Rmd
modules/Statistics/lab/Statistics_Lab_Key.Rmd
resources/dictionary.txt

Resloves #322
- adding some more plots and info about correlation
- adding relevant case studies to each section
- showing more about making results tidy
- tiny bit of theory on the slides just to give more context

Stats updates

---

config.yml

Needed to add Clif to the config too.

adding Clif to the list of instructors

---

config.yml

ugh doing too many things at once...

fix spacing for clif

---

materials_schedule.Rmd
modules/HW/homework2.Rmd
modules/HW/homework3.Rmd
syllabus.Rmd

Homework bug

---

modules/Subsetting_Data_in_R/Subsetting_Data_in_R.Rmd
modules/Subsetting_Data_in_R/lab/Subsetting_Data_in_R_Lab.Rmd
modules/Subsetting_Data_in_R/lab/Subsetting_Data_in_R_Lab_Key.Rmd

resolves #303 
- rearranged the labs a bit to make just 3 parts instead of 2 - it was a tad awkward last time. Hopefully there aren't too many questions now. 
- made which() an extra slide and added where()

Subsetting sum 23

---

syllabus.Rmd

adding course eval to syllabus

---

syllabus.Rmd

fixing typo

---

modules/Project_Guidelines/Project_Guidelines.Rmd
resources/dictionary.txt

making ggplot2 a requirement and adding CDC, tidytuesdayR, and healthdata.gov
resolves #352 
resolves #354 
resolves #313

Updating Project Guidelines

---

materials_schedule.Rmd

Address #409

---

modules/Data_Visualization/lab/Data_Visualization_Lab.Rmd
modules/Data_Visualization/lab/Data_Visualization_Lab_Key.Rmd

I had more commits to this branch but they are stuck (never had this happen quite like this)... so going to finish updates in another branch
resolves #337

DataViz - fixing lab and adding more cake images

---

modules/Data_Visualization/Data_Visualization.Rmd

resolves #295 if the concern was about showing more examples of reading in data

reading in food data and fixing cheatsheet on slide

---

modules/Functions/Functions.Rmd
modules/Functions/lab/Functions_Lab.Rmd
modules/Functions/lab/Functions_Lab_Key.Rmd

Address Functions issues 349 and 441

---

.github/workflows/docker-test.yml
.github/workflows/manual_dispatch.yml

Update docker stuff

---

modules/Data_Classes/Data_Classes.Rmd

adding a mutate example to classes

---

modules/Data_Cleaning/Data_Cleaning.Rmd
modules/Data_Cleaning/lab/Data_Cleaning_Lab.Rmd
modules/Data_Cleaning/lab/Data_Cleaning_Lab_Key.Rmd

- getting rid of airqual data for just bike
-  moving recode to extra slides and removing it from the lab

only bike data and no recode for cleaning

---

modules/Manipulating_Data_in_R/Manipulating_Data_in_R.Rmd
modules/Manipulating_Data_in_R/lab/Manipulating_Data_in_R_Lab.Rmd
modules/Manipulating_Data_in_R/lab/Manipulating_Data_in_R_Lab_Key.Rmd

Resolving updates / notes from June 2023 :)

Addressing Manipulation updates ahead of Tues (tomorrow)

---

modules/Manipulating_Data_in_R/Manipulating_Data_in_R.Rmd
resources/dictionary.txt

I think it's working now, yay! Undoing small tweaks to trigger build.

Undo test change (to see if pdf rendering was working correctly)

---

GA_Script.Rhtml
_site.yml

Adding Google Analytics capability

Add Google Analytics

---

modules/RStudio/RStudio.Rmd
modules/Subsetting_Data_in_R/Subsetting_Data_in_R.Rmd
modules/Subsetting_Data_in_R/index_withbase.Rmd

Fix some lingering URL issues

---

scripts/render_html_list.R

Update render html list to exclude HWs

---

modules/Data_Summarization/Data_Summarization.Rmd
modules/Data_Summarization/lab/Data_Summarization_Lab_Key.Rmd

Updating module content - Summarization

---

modules/Data_Output/lab/Data_Output_Lab_Key.Rmd
modules/Esquisse_Data_Visualization/Esquisse_Data_Visualization.Rmd
modules/Statistics/Statistics.Rmd

[DaSEH Content Update] Output, Stats

---

modules/Factors/Factors.Rmd

[DaSEH Content Update] Factors

---

help.Rmd

the header only had half the `**` for bolding

fixing header about color/theme change

---

modules/Subsetting_Data_in_R/Subsetting_Data_in_R.Rmd

the link got cutoff in the slides - fixing that

fixing line cutoff of link

---

modules/Data_Cleaning/Data_Cleaning.Rmd

- just making some slides look better and removing some old info

Cleaning sum 24

---

modules/Data_Cleaning/Data_Cleaning.Rmd

- changing out the column names and renaming the object to be more generic and a different range so it is likely not weight but could be blood sugar or something

adding cleaning lecture material with more generic data - not diet

---

modules/Basic_R/lab/Basic_R_Lab_Key.Rmd

- Remove carried over objects : reduce struggle in case R object is not retained on day 2

Remove carried over object in Basic R lab

---

modules/RStudio/lab/RStudio_Lab_Key.Rmd

Clarify RStudio lab

---

modules/Data_Visualization/lab/Data_Visualization_Lab_Key.Rmd
resources.Rmd

- resolves https://github.com/jhudsl/intro_to_r/issues/618
- resolves #617

[website updates] winter 25

---

config.yml
docs/module_details/day0.Rmd
modules/Setup/Setup.Rmd
resources/email_to_class.txt

just helping you start this @avahoffman :) so that is less stressful when you get back

adding some updates for the email

---

modules/Intro/Intro.Rmd

removing hutch training lead info

Update Carrie's info

---

modules/RStudio/RStudio.Rmd
modules/RStudio/lab/RStudio_Lab.Rmd
modules/RStudio/lab/RStudio_Lab_Key.Rmd

- need to remove more about jhur stuff from the lab
- also wanted the summary slide info to fit

Lastmin rstudio

---

modules/Factors/Factors.Rmd
modules/Factors/lab/Factors_Lab_Key.Rmd

- Remove `mapping` from key & lab
- Resolves #599

Factors Update

---

modules/Data_Input/lab/Data_Input_Lab_Key.Rmd

Addressing minor issues, not big content changes

---

.github/workflows/manual_dispatch.yml

Updating this workflow so that we can keep on top of the docker image. DaSEH updates coming next.

Update workflow for docker image

---

.github/workflows/manual_dispatch.yml
.github/workflows/pull_request.yml
.github/workflows/render-site.yml
config_automation.yml

Catching this repo up to changes in OTTR and other repos.
FYI @carriewright11 @clifmckee

Fix some actions rendering issues

---

modules/Data_Summarization/Data_Summarization.Rmd
modules/Subsetting_Data_in_R/Subsetting_Data_in_R.Rmd
modules/Subsetting_Data_in_R/lab/Subsetting_Data_in_R_Lab_Key.Rmd

addresses #658 for subsetting
- simplifying renaming section
- removing `order` and `everything` (and instead just do `relocate`)

summer 2025 subsetting 
